### ISSUE TITLE
Issue having multiple has_one relationships in a calculation

### ISSUE THREAD

**Issue by ahey** [ash-project/ash_postgres#177]
**Describe the bug**

Including two `has_one` relationships in a calculation, where both of those relationships are backed by the same resource causes an error.

**To Reproduce**
 I have created [a failing test that demonstrates the issue in this branch](https://github.com/ahey/ash_postgres/tree/complex-has-one-calculation).

The error produced when the test is run is:

```bash
 1) test channel: first_member and second member (AshPostgres.Test.ComplexCalculationsTest)
     test/complex_calculations_test.exs:63
     ** (RuntimeError) Error while building reference: second_member.user_id
     code: |> AshPostgres.Test.ComplexCalculations.Api.load!(:name, actor: user_1)
     stacktrace:
       (ash_postgres 1.3.61) lib/expr.ex:1278: AshPostgres.Expr.do_dynamic_expr/5
       (ash_postgres 1.3.61) lib/expr.ex:625: AshPostgres.Expr.do_dynamic_expr/5
       (ash_postgres 1.3.61) lib/expr.ex:369: AshPostgres.Expr.do_dynamic_expr/5
       (ash_postgres 1.3.61) lib/expr.ex:375: AshPostgres.Expr.do_dynamic_expr/5
       (ash_postgres 1.3.61) lib/expr.ex:1012: anonymous fn/6 in AshPostgres.Expr.do_dynamic_expr/5
       (ecto 3.10.3) lib/ecto/query/builder/dynamic.ex:76: Ecto.Query.Builder.Dynamic.expand/3
       (stdlib 5.0.2) lists.erl:1706: :lists.mapfoldl_1/3
       (elixir 1.15.4) lib/macro.ex:653: Macro.do_traverse/4
       (ecto 3.10.3) lib/ecto/query/builder/dynamic.ex:59: Ecto.Query.Builder.Dynamic.partially_expand/6
       (ecto 3.10.3) lib/ecto/query/builder/select.ex:235: Ecto.Query.Builder.Select.expand_nested/3
       (ecto 3.10.3) lib/ecto/query/builder/select.ex:274: Ecto.Query.Builder.Select.expand_nested_pair/3
       (elixir 1.15.4) lib/enum.ex:1825: anonymous fn/3 in Enum.map_reduce/3
       (stdlib 5.0.2) maps.erl:416: :maps.fold_1/4
       (elixir 1.15.4) lib/enum.ex:2522: Enum.map_reduce/3
       (ecto 3.10.3) lib/ecto/query/builder/select.ex:257: Ecto.Query.Builder.Select.expand_nested/3
       (ecto 3.10.3) lib/ecto/query/builder/select.ex:205: Ecto.Query.Builder.Select.select!/5
       (ash_postgres 1.3.61) lib/calculation.ex:82: AshPostgres.Calculation.add_calculations/4
       (ash 2.17.1) lib/ash/actions/read.ex:3306: Ash.Actions.Read.run_calculation_query/6
       (ash 2.17.1) lib/ash/actions/read.ex:3006: anonymous fn/11 in Ash.Actions.Read.calculation_request/14
       (ash 2.17.1) lib/ash/engine/engine.ex:537: anonymous fn/2 in Ash.Engine.run_iteration/1
       (ash 2.17.1) lib/ash/engine/engine.ex:558: anonymous fn/4 in Ash.Engine.async/2
       (elixir 1.15.4) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2
       (elixir 1.15.4) lib/task/supervised.ex:36: Task.Supervised.reply/4
       (ash 2.17.1) lib/ash/engine/engine.ex:552: Ash.Engine.async/2
       (elixir 1.15.4) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
       (ash 2.17.1) lib/ash/engine/engine.ex:702: Ash.Engine.start_pending_tasks/1
       (ash 2.17.1) lib/ash/engine/engine.ex:323: Ash.Engine.run_to_completion/1
       (ash 2.17.1) lib/ash/engine/engine.ex:252: Ash.Engine.do_run/2
       (ash 2.17.1) lib/ash/engine/engine.ex:148: Ash.Engine.run/2
       (ash 2.17.1) lib/ash/actions/read.ex:200: Ash.Actions.Read.do_run/3
       (ash 2.17.1) lib/ash/actions/read.ex:97: anonymous fn/3 in Ash.Actions.Read.run/3
       (ash 2.17.1) lib/ash/actions/read.ex:96: Ash.Actions.Read.run/3
       (ash 2.17.1) lib/ash/api/api.ex:1832: Ash.Api.load/4
       (ash 2.17.1) lib/ash/api/api.ex:1801: Ash.Api.load!/4
       test/complex_calculations_test.exs:105: (test)
```

**Expected behavior**

**Comment by ahey** [comment]
Hey @zachdaniel , thank you for looking into it! This has fixed the compilation error, however the [test is still failing due to the calculation returning the wrong value](https://github.com/ash-project/ash_postgres/actions/runs/6893460513/job/18753143332#step:12:742). This is also occurring for me locally.

**Comment by zachdaniel** [comment]
Yep! Meant to update this issue. I'm investigating currently.

**Comment by zachdaniel** [comment]
Can you try out main for me?

**Comment by ahey** [comment]
Sure – same issue :(

```elixir
1) test channel: first_member and second member (AshPostgres.Test.ComplexCalculationsTest)
     test/complex_calculations_test.exs:64
     Assertion with == failed
     code:  assert channel.name == user_2.name
     left:  "User 1, User 2"
     right: "User 2"
     stacktrace:
       test/complex_calculations_test.exs:114: (test)
```

**Comment by zachdaniel** [comment]
Sorry, I think I hadn't pushed up the fix 🤦 I pushed it up just now with another separate fix.

**Comment by ahey** [comment]
OK this is making more sense now. I was running postgres v13.3 locally, and the test fails on that version. The github workflow uses latest postgres which is 16.1, and the test is passing. I installed 16.1 locally and the test does indeed pass!

We might therefore need to bump the minimum version of postgres supported by `ash_postgres` (currently 10), or find out why it doesn't work on v13.3.

I'm able to use a newer version of postgres in this project so this is solved for me now 🥳

**Comment by zachdaniel** [comment]
Interestinggggggg. I'm going to add version 10 and 13.3 to our testing matrix I think.

**Comment by zachdaniel** [comment]
I really can't see why this would be a problem on pg 13 😢

**Comment by ahey** [comment]
I have tested locally, and your latest commits to `ash_postgres` appear to have fixed the issue on all postgres versions 🥳 

Thank you 😄
